[package]
name = "egui_glfw_integ"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.19.0"
glfw = "0.45.0"
gl = "0.14.0"
cli-clipboard = "0.2.1"